// <auto-generated />
using System;
using ISO_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISO_Manager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISO_Manager.Models.Ambulance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("car_model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rental_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("workplace_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.HasIndex("workplace_id");

                    b.ToTable("Ambulances");
                });

            modelBuilder.Entity("ISO_Manager.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("asset_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("device_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("inspection_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("inspector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serial_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ISO_Manager.Models.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("asset_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("device_owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("device_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_calibration")
                        .HasColumnType("datetime2");

                    b.Property<string>("serial_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_calibration")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calibrations");
                });

            modelBuilder.Entity("ISO_Manager.Models.Cartable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cartables");
                });

            modelBuilder.Entity("ISO_Manager.Models.Cloth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("cloth_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("receive_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("receive_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("size")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("ISO_Manager.Models.ClothGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClothGroups");
                });

            modelBuilder.Entity("ISO_Manager.Models.ClothGroupList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("boiler_suit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cloth_group_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("shoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("cloth_group_id");

                    b.HasIndex("user_id");

                    b.ToTable("ClothGroupLists");
                });

            modelBuilder.Entity("ISO_Manager.Models.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contract_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employer_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("hse_agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hse_agent_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_agent_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("personnel_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("ISO_Manager.Models.ContractorAccident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("accident_boss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_complication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_consequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("accident_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("accident_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("accident_hour")
                        .HasColumnType("time");

                    b.Property<string>("accident_injured_part")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activity_in_accident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("contractor_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("direct_accident_causes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hse_boss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hse_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("is_guilty")
                        .HasColumnType("smallint");

                    b.Property<int?>("lost_days")
                        .HasColumnType("int");

                    b.Property<string>("marriage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("receive_report_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("scan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unsafe_action_causes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unsafe_condition_causes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("contractor_id");

                    b.HasIndex("user_id");

                    b.ToTable("ContractorAccidents");
                });

            modelBuilder.Entity("ISO_Manager.Models.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("camp_boss_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rig_boss_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("camp_boss_id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("rig_boss_id");

                    b.ToTable("DailyReports");
                });

            modelBuilder.Entity("ISO_Manager.Models.Duty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<double?>("step")
                        .HasColumnType("float");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("ISO_Manager.Models.EmergencyPhoneBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("city_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("organization_id")
                        .HasColumnType("int");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmergencyPhoneBooks");
                });

            modelBuilder.Entity("ISO_Manager.Models.EmergencyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("duty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("duty_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("workplace_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("duty_id");

                    b.HasIndex("user_id");

                    b.HasIndex("workplace_id");

                    b.ToTable("EmergencyTeams");
                });

            modelBuilder.Entity("ISO_Manager.Models.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("contractor_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("examination_date")
                        .HasColumnType("int");

                    b.Property<string>("examination_result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("contractor_id");

                    b.HasIndex("user_id");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("ISO_Manager.Models.HarmfulFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HarmfulFactor");
                });

            modelBuilder.Entity("ISO_Manager.Models.HarmfulItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("harmful_factor_id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("harmful_factor_id");

                    b.ToTable("HarmfulItem");
                });

            modelBuilder.Entity("ISO_Manager.Models.HealthCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("workplace_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.HasIndex("workplace_id");

                    b.ToTable("HealthCarts");
                });

            modelBuilder.Entity("ISO_Manager.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("inspection_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("inspection_place_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("workplace_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("inspection_place_id");

                    b.HasIndex("user_id");

                    b.HasIndex("workplace_id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("ISO_Manager.Models.InspectionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("inspection_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("inspection_id")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("text_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("workplace_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("inspection_id");

                    b.HasIndex("text_id");

                    b.HasIndex("workplace_id");

                    b.ToTable("InspectionDetails");
                });

            modelBuilder.Entity("ISO_Manager.Models.InspectionPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InspectionPlaces");
                });

            modelBuilder.Entity("ISO_Manager.Models.InspectionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("inspection_place_id")
                        .HasColumnType("int");

                    b.Property<int?>("step")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("inspection_place_id");

                    b.ToTable("InspectionTexts");
                });

            modelBuilder.Entity("ISO_Manager.Models.LegalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("regulation_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LegalRequirements");
                });

            modelBuilder.Entity("ISO_Manager.Models.Maneuver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("act_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Maneuvers");
                });

            modelBuilder.Entity("ISO_Manager.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("receiver_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sender_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("receiver_id");

                    b.HasIndex("sender_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ISO_Manager.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("occupation_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occupation_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("ISO_Manager.Models.OccupationHarmful", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HarmfulItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("evaluation_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exposure_duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exposure_limit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exposure_rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exposure_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("harmful_factor_id")
                        .HasColumnType("int");

                    b.Property<int?>("harmful_item_id")
                        .HasColumnType("int");

                    b.Property<int?>("occupation_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HarmfulItemId");

                    b.HasIndex("harmful_factor_id");

                    b.HasIndex("occupation_id");

                    b.ToTable("OccupationHarmfuls");
                });

            modelBuilder.Entity("ISO_Manager.Models.OfficialAccident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("accident_boss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_complication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_consequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("accident_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("accident_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("accident_hour")
                        .HasColumnType("time");

                    b.Property<string>("accident_injured_part")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accident_place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activity_in_accident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("direct_accident_causes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("examination_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("hse_boss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hse_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("is_guilty")
                        .HasColumnType("smallint");

                    b.Property<int?>("lost_days")
                        .HasColumnType("int");

                    b.Property<string>("marriage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("receive_report_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("scan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unsafe_action_causes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unsafe_condition_causes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("OfficialAccidents");
                });

            modelBuilder.Entity("ISO_Manager.Models.OperationPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("accept_percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("done")
                        .HasColumnType("int");

                    b.Property<int?>("estimate")
                        .HasColumnType("int");

                    b.Property<decimal?>("plan_percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("plan_realization_percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("purpose_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("realization_percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("purpose_id");

                    b.ToTable("OperationPlans");
                });

            modelBuilder.Entity("ISO_Manager.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ISO_Manager.Models.Permit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permit_attachment_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("permit_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("permit_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permit_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permits");
                });

            modelBuilder.Entity("ISO_Manager.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("ISO_Manager.Models.ProcessPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("accept_percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("deviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("plan_percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("process_id")
                        .HasColumnType("int");

                    b.Property<string>("requests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("process_id");

                    b.ToTable("ProcessPlans");
                });

            modelBuilder.Entity("ISO_Manager.Models.Purpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Purposes");
                });

            modelBuilder.Entity("ISO_Manager.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("reminder_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("ISO_Manager.Models.RigAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("asset_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("count_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("default_count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exist_count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RigAssets");
                });

            modelBuilder.Entity("ISO_Manager.Models.Standard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("fa_chapter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fa_subchapter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fa_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Standards");
                });

            modelBuilder.Entity("ISO_Manager.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("employment_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("occupation_id")
                        .HasColumnType("int");

                    b.Property<int?>("organization_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("workplace_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("occupation_id");

                    b.HasIndex("organization_id");

                    b.HasIndex("user_id")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.HasIndex("workplace_id");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("ISO_Manager.Models.UserPermit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("UserPermits");
                });

            modelBuilder.Entity("ISO_Manager.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ISO_Manager.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("employment_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("national_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("register_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.Ambulance", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.HasOne("ISO_Manager.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("workplace_id");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ISO_Manager.Models.Cloth", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.ClothGroupList", b =>
                {
                    b.HasOne("ISO_Manager.Models.ClothGroup", "ClothGroup")
                        .WithMany()
                        .HasForeignKey("cloth_group_id");

                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("ClothGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.ContractorAccident", b =>
                {
                    b.HasOne("ISO_Manager.Models.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("contractor_id");

                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("Contractor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.DailyReport", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "CampBoss")
                        .WithMany()
                        .HasForeignKey("camp_boss_id");

                    b.HasOne("ISO_Manager.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("doctor_id");

                    b.HasOne("ISO_Manager.Models.User", "RigBoss")
                        .WithMany()
                        .HasForeignKey("rig_boss_id");

                    b.Navigation("CampBoss");

                    b.Navigation("Doctor");

                    b.Navigation("RigBoss");
                });

            modelBuilder.Entity("ISO_Manager.Models.EmergencyTeam", b =>
                {
                    b.HasOne("ISO_Manager.Models.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("duty_id");

                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.HasOne("ISO_Manager.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("workplace_id");

                    b.Navigation("Duty");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ISO_Manager.Models.Examination", b =>
                {
                    b.HasOne("ISO_Manager.Models.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("contractor_id");

                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("Contractor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.HarmfulItem", b =>
                {
                    b.HasOne("ISO_Manager.Models.HarmfulFactor", "HarmfulFactor")
                        .WithMany()
                        .HasForeignKey("harmful_factor_id");

                    b.Navigation("HarmfulFactor");
                });

            modelBuilder.Entity("ISO_Manager.Models.HealthCart", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.HasOne("ISO_Manager.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("workplace_id");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ISO_Manager.Models.Inspection", b =>
                {
                    b.HasOne("ISO_Manager.Models.InspectionPlace", "InspectionPlace")
                        .WithMany()
                        .HasForeignKey("inspection_place_id");

                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.HasOne("ISO_Manager.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("workplace_id");

                    b.Navigation("InspectionPlace");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ISO_Manager.Models.InspectionDetail", b =>
                {
                    b.HasOne("ISO_Manager.Models.Inspection", "Inspection")
                        .WithMany("InspectionDetails")
                        .HasForeignKey("inspection_id");

                    b.HasOne("ISO_Manager.Models.InspectionText", "InspectionText")
                        .WithMany()
                        .HasForeignKey("text_id");

                    b.HasOne("ISO_Manager.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("workplace_id");

                    b.Navigation("Inspection");

                    b.Navigation("InspectionText");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ISO_Manager.Models.InspectionText", b =>
                {
                    b.HasOne("ISO_Manager.Models.InspectionPlace", "InspectionPlace")
                        .WithMany()
                        .HasForeignKey("inspection_place_id");

                    b.Navigation("InspectionPlace");
                });

            modelBuilder.Entity("ISO_Manager.Models.Message", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("receiver_id");

                    b.HasOne("ISO_Manager.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("sender_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ISO_Manager.Models.OccupationHarmful", b =>
                {
                    b.HasOne("ISO_Manager.Models.HarmfulItem", "HarmfulItem")
                        .WithMany()
                        .HasForeignKey("HarmfulItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISO_Manager.Models.HarmfulFactor", "HarmfulFactor")
                        .WithMany()
                        .HasForeignKey("harmful_factor_id");

                    b.HasOne("ISO_Manager.Models.Occupation", "Occupation")
                        .WithMany()
                        .HasForeignKey("occupation_id");

                    b.Navigation("HarmfulFactor");

                    b.Navigation("HarmfulItem");

                    b.Navigation("Occupation");
                });

            modelBuilder.Entity("ISO_Manager.Models.OfficialAccident", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.OperationPlan", b =>
                {
                    b.HasOne("ISO_Manager.Models.Purpose", "Purpose")
                        .WithMany()
                        .HasForeignKey("purpose_id");

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("ISO_Manager.Models.ProcessPlan", b =>
                {
                    b.HasOne("ISO_Manager.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("ISO_Manager.Models.Reminder", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISO_Manager.Models.UserInfo", b =>
                {
                    b.HasOne("ISO_Manager.Models.Occupation", "Occupation")
                        .WithMany()
                        .HasForeignKey("occupation_id");

                    b.HasOne("ISO_Manager.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("organization_id");

                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithOne("UserInfos")
                        .HasForeignKey("ISO_Manager.Models.UserInfo", "user_id");

                    b.HasOne("ISO_Manager.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("workplace_id");

                    b.Navigation("Occupation");

                    b.Navigation("Organization");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ISO_Manager.Models.UserPermit", b =>
                {
                    b.HasOne("ISO_Manager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ISO_Manager.Models.Inspection", b =>
                {
                    b.Navigation("InspectionDetails");
                });

            modelBuilder.Entity("ISO_Manager.Models.User", b =>
                {
                    b.Navigation("UserInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
